### ISSUE TITLE
Hardcoded to RN50?

### ISSUE THREAD

**Issue by afiaka87** [Zasder3/train-CLIP-FT#3]
https://github.com/Zasder3/train-CLIP-FT/blob/6fc671efe4a98008c79a10c48b0f797dc005e76b/models/wrapper.py#L164

I assume this needs to be changed to the correct config if you are finetuning e.g. `ViT-B/32` - is that correct?

**Comment by Zasder3** [comment]
That line is just there for OOP purposes it's my hacky way of initializing an "empty" model so to speak. All model-specific variables are overridden in the `train_finetune.py`. Luckily no need to worry the string you specify in the main file is what you will be training!
